name: sgnm-neo4j-excel

on:
  push:
    branches: [ "main" ]
      
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to repository
        uses: actions/checkout@v3
      - name: install and build
        run: npm ci --force
      - name: publish to registry
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npm.js.org
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
